import { Button, MenuItem, Select } from '@mui/material';
import { setAdminVenueStatus, setBusinessAccess } from '../../api/admin';
import { useAdminAction, useAdminAudit, useAdminBusinesses, useAdminCustomers, useAdminVenues } from '../../hooks/useAdmin';

const Shell=({title,children})=><><p className="eyebrow">Platform management</p><h1 className="mt-2 text-3xl font-black">{title}</h1><div className="surface-card mt-7 overflow-x-auto">{children}</div></>;
const Table=({head,children})=><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-line bg-canvas text-xs uppercase text-muted"><tr>{head.map(x=><th key={x} className="p-4">{x}</th>)}</tr></thead><tbody className="divide-y divide-line">{children}</tbody></table>;
export function AdminBusinessesPage(){const {data=[]}=useAdminBusinesses();const action=useAdminAction(({id,params})=>setBusinessAccess(id,params),['admin-businesses','admin-dashboard']);return <Shell title="Businesses"><Table head={['Business','Owner','Venues','Commission','Access']} >{data.map(x=><tr key={x.id}><td className="p-4 font-bold">{x.name}</td><td className="p-4">{x.ownerEmail}</td><td className="p-4">{x.venueCount}</td><td className="p-4">{x.commissionPercent}%</td><td className="p-4"><Button color={x.enabled&&!x.locked?'error':'success'} onClick={()=>action.mutate({id:x.id,params:{enabled:!x.enabled,locked:x.enabled,reason:'Changed in admin portal'}})}>{x.enabled&&!x.locked?'Suspend':'Enable'}</Button></td></tr>)}</Table></Shell>}
export function AdminVenuesPage(){const {data=[]}=useAdminVenues();const action=useAdminAction(({id,status})=>setAdminVenueStatus(id,{status,reason:'Changed in admin portal'}),['admin-venues','admin-dashboard']);return <Shell title="Venues"><Table head={['Venue','Business','City','Type','Status']} >{data.map(x=><tr key={x.id}><td className="p-4 font-bold">{x.name}</td><td className="p-4">{x.businessName}</td><td className="p-4">{x.city}</td><td className="p-4">{x.venueType}</td><td className="p-4"><Select size="small" value={x.status} onChange={e=>action.mutate({id:x.id,status:e.target.value})}>{['PENDING_APPROVAL','APPROVED','ACTIVE','REJECTED','SUSPENDED','INACTIVE'].map(s=><MenuItem key={s} value={s}>{s.replaceAll('_',' ')}</MenuItem>)}</Select></td></tr>)}</Table></Shell>}
export function AdminCustomersPage(){const {data=[]}=useAdminCustomers();return <Shell title="Customers"><Table head={['Name','Email','Phone','Status']} >{data.map(x=><tr key={x.id}><td className="p-4 font-bold">{x.firstName} {x.lastName}</td><td className="p-4">{x.email}</td><td className="p-4">{x.phone}</td><td className="p-4">{x.status}</td></tr>)}</Table></Shell>}
export function AdminAuditPage(){const {data=[]}=useAdminAudit();return <Shell title="Audit log"><Table head={['Time','Administrator','Action','Resource','Reason']} >{data.map(x=><tr key={x.id}><td className="p-4">{new Date(x.createdAt).toLocaleString()}</td><td className="p-4">{x.adminEmail}</td><td className="p-4 font-bold">{x.action.replaceAll('_',' ')}</td><td className="p-4">{x.resourceType} · {x.resourceId}</td><td className="p-4">{x.reason||'—'}</td></tr>)}</Table></Shell>}
